name: to-pages
on:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
      
    - name: Build
      run : |
        echo 'some build actions'
        rm -rf dist
        mkdir -p dist
        cp assets/** dist/
        ls ./dist/
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        single-commit: true

# EOF
